### PR TITLE
[RFC] Add jplephem based ephemeris.

### PR DESCRIPTION
**Pull request by helgee**
ToDo:
- [ ] Documentation
- [x] Testing the actual ephemeris calculations

### CODE REVIEW

**Comment by RazerM** [comment]
It might be worthwhile to allow passing an object to target/origin.

Thus, the API would look like this:

```
ephemeris.rv(origin=earth, ...)
ephemeris.rv(origin=earth.barycenter, ...)
```

I would propose implement this using a namedtuple:

```
NAIFID = namedtuple('NAIFID', ['name', 'code'])
```

The `CelestialBody` classes would gain two new attributes:

```
>>> from astrodynamics.bodies import earth
>>> earth.naif_id
NAIFID(name='EARTH', code=399)
>>> earth.barycenter
NAIFID(name='EARTH BARYCENTER', code=3)
```

The ephemeris code could pass origin and target through a function to extract the integer like so:

```
origin = get_naif_id(origin)

def get_naif_id(obj):
    if isinstance(obj, CelestialBody):
        return obj.naif_id.code
    elif isinstance(obj, NAIFID):
        return obj.code
    else:
        return obj
```

**Comment by RazerM** [comment]
Implementation detail:
- Should we instantiate a bunch of NAIFID instances?
  
  Then astrodynamics.bodies imports the relevant ones for assigning to `earth.naif_id` and `earth.barycenter`

Another thought:
- Should tdb require an `astropy.time.Time` object?

**Comment by helgee** [comment]
I consider the emphemeris a low-level element that is not part of the user-facing API and therefore would be okay with passing it raw integers and floats. My idea for its integration with the rest of the library looks like this:
- The `CelestialBody` objects get an integer-valued `naif_id` attribute.
- The `CelestialBody` and `State` get a `wrt` method which then calls the ephemeris.

``` python
# CelestialBody; returns r & v numpy arrays
def wrt(self, body, t):
    return ephemeris.rv(self.naif_id, body.naif_id, t.jd1, t.jd2)

# State; returns a new State
def wrt(self, body):
    r, v = ephemeris.rv(self.body.naif_id, body.naif_id, self.t.jd1, self.t.jd2)
    return State(r, v, self.t, body, ...)
```

**Comment by RazerM** [comment]
That makes sense. In that case, should this module move to `astrodynamics.lowlevel.ephemerides` a la `cryptography.hazmat.*`?

I think keeping non user-facing API in the lowlevel package will make the user-facing API easier to understand.

**Comment by helgee** [comment]
I have not thought about this approach, yet. Sounds reasonable though.

@Juanlu001 What do you think?

**Comment by RazerM** [comment]
@helgee @Juanlu001 I think it was mentioned briefly before about any functions that don't use units.

**Comment by helgee** [comment]
:+1:  from me then.

**Comment by astrojuanlu** [comment]
:+1: from me too!

**Comment by RazerM** [comment]
@helgee Can you create a branch in the main repo? You can still open a pull request to master.

I started writing some documentation, would be good if I could commit to the branch and have it show up in the pull request.

**Comment by helgee** [comment]
Done. Closing this then.

**Pull request closed without merging**
