### PR TITLE
[RFC] Add jplephem based ephemeris.

### PR DESCRIPTION
**Pull request by helgee**
See previous discussion in #7.

### CODE REVIEW

**Comment by helgee** [comment]
Building `networkx` with 3.X on Windows seems to fail due to some missing example file (!) :-1:

**Comment by RazerM** [comment]
Odd. The file is present in git, I don't know what is causing the error. Perhaps some bug in `install_data` command.

**Comment by RazerM** [comment]
I found the issue: https://github.com/networkx/networkx/pull/1707

I think we're waiting on v1.10.1

**Comment by helgee** [comment]
Should we use the dev version of networkx for now? I am actually using just a single function but might need it in another place as well.

**Comment by RazerM** [comment]
networkx issue is gone now

**Comment by helgee** [comment]
Ready to merge, then?

**Comment by RazerM** [comment]
:+1:

**Pull request merged**
